SELECT* FROM [dbo].[TB_ACT_OLIST_CUSTOMER]

ALTER VIEW VW_PEDIDOS_POR_CLIENTE
AS

SELECT O.*, C.CUSTOMER_CITY
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [dbo].[TB_ACT_OLIST_CUSTOMER] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID 
WHERE ORDER_STATUS ='DELIVERED'

SELECT * FROM VW_PEDIDOS_POR_CLIENTE